import React, { useEffect, useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppContext } from '../store/AppContext';
import type { BakeryPayment } from '../store/types';
import { ArrowLeft, Printer, Share2 } from 'lucide-react';
import html2canvas from 'html2canvas';

import QRCodeImport from 'react-qr-code';
const QRCode = (QRCodeImport as any).default || QRCodeImport;

export const BakeryReceipt: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { bakeryPayments, appSettings, companyMetrics } = useAppContext();
  
  const [payment, setPayment] = useState<BakeryPayment | null>(null);
  const receiptRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (id) {
      const found = bakeryPayments.find(p => p.id === id);
      if (found) {
        setPayment(found);
      }
    }
  }, [id, bakeryPayments]);

  if (!payment) {
    return (
      <div className="container p-6 text-center">
        <h2 className="text-xl font-bold mb-4">Receipt Not Found</h2>
        <button className="btn btn-primary" onClick={() => navigate('/inventory')}>Back to Inventory</button>
      </div>
    );
  }

  // To show an accurate "remaining balance", we calculate what the balance is now.
  // Note: this represents the CURRENT balance, which is usually exactly what they want on the receipt.
  const currentBalance = companyMetrics.totalValueReceived - companyMetrics.totalMoneyPaid;

  const handlePrint = async () => {
    // Try Bluetooth printing first, fallback to standard print
    try {
      if (!(navigator as any).bluetooth) throw new Error("Web Bluetooth not supported.");
      
      const device = await (navigator as any).bluetooth.requestDevice({
        filters: [{ services: ['000018f0-0000-1000-8000-00805f9b34fb'] }],
        optionalServices: ['000018f0-0000-1000-8000-00805f9b34fb']
      });

      const server = await device.gatt?.connect();
      if (!server) throw new Error("Could not connect to GATT server.");
      
      const services = await server.getPrimaryServices();
      if (services.length === 0) throw new Error("No services found.");
      const service = services[0];
      
      const characteristics = await service.getCharacteristics();
      const characteristic = characteristics.find((c: any) => c.properties.write || c.properties.writeWithoutResponse);
      if (!characteristic) throw new Error("No writable characteristic.");

      // Build ESC/POS payload
      const title = (appSettings.companyName || 'BREAD APP').toUpperCase();
      let cmds = [
        "\\x1B" + "@", // Init
        "\\x1B" + "a" + "\\x01", // Center
        "\\x1B" + "E" + "\\x01", // Bold
        title + "\n",
        "\\x1B" + "E" + "\\x00", // Normal
        "SUPPLIER PAYMENT RECEIPT\n",
        "--------------------------------\n", // 32 chars
        "\\x1B" + "a" + "\\x00", // Left
        `Receipt: #${payment.id.slice(-6).toUpperCase()}\n`,
        `Date: ${new Date(payment.date).toLocaleString()}\n`,
        `Method: ${payment.method || 'Cash'}\n`,
      ];
      
      if (payment.receiver) cmds.push(`Receiver: ${payment.receiver}\n`);
      cmds.push("--------------------------------\n");
      
      cmds.push("\\x1B" + "a" + "\\x01", "AMOUNT PAID\n"); // Center
      
      cmds.push("\\x1B" + "E" + "\\x01"); // Bold
      cmds.push("\\x1D" + "!" + "\\x11"); // Double height/width
      cmds.push(`N ${payment.amount.toLocaleString()}\n`);
      cmds.push("\\x1D" + "!" + "\\x00"); // Normal
      cmds.push("\\x1B" + "E" + "\\x00"); // Unbold
      
      cmds.push("\\x1B" + "a" + "\\x00"); // Left align
      cmds.push("--------------------------------\n");
      cmds.push(`Cur Balance: N ${currentBalance.toLocaleString()}\n`);
      
      cmds.push("\\x1B" + "a" + "\\x01"); // Center
      cmds.push("\n");
      cmds.push((appSettings.receiptFooter || 'Thank you for your business!') + "\n");
      cmds.push("Generated by BreadApp\n");
      cmds.push("\n\n\n"); // Feed paper

      const cmdStr = cmds.join("");
      const buffer = [];
      for (let i = 0; i < cmdStr.length; i++) {
        if (cmdStr[i] === '\\' && cmdStr[i+1] === 'x') {
           buffer.push(parseInt(cmdStr.substring(i+2, i+4), 16));
           i += 3;
        } else {
           buffer.push(cmdStr.charCodeAt(i));
        }
      }
      
      const payload = new Uint8Array(buffer);
      const chunkSize = 32;
      for (let i = 0; i < payload.length; i += chunkSize) {
        const chunk = payload.slice(i, i + chunkSize);
        if (characteristic.properties.writeWithoutResponse) {
           await characteristic.writeValueWithoutResponse(chunk);
        } else {
           await characteristic.writeValue(chunk);
        }
        await new Promise(r => setTimeout(r, 20));
      }

      await new Promise(r => setTimeout(r, 500));
      device.gatt.disconnect();

    } catch (error) {
      console.warn("Bluetooth print failed: ", error);
      window.print();
    }
  };

  const handleShare = async () => {
    if (!receiptRef.current) return;
    
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 2 });
      canvas.toBlob(async (blob) => {
        if (!blob) return;
        const file = new File([blob], `bakery-receipt-${payment.id}.png`, { type: 'image/png' });
        
        if (navigator.share) {
          await navigator.share({
            title: 'Bakery Payment Receipt',
            files: [file]
          });
        } else {
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `bakery-receipt-${payment.id}.png`;
          a.click();
          URL.revokeObjectURL(url);
        }
      });
    } catch (err) {
      console.error('Error sharing receipt:', err);
      alert('Could not generate image for sharing.');
    }
  };

  return (
    <div className="container pb-20" style={{ maxWidth: '320px', margin: '0 auto', background: 'var(--surface-color)', minHeight: '100vh', paddingTop: '1rem' }}>
      <div className="flex justify-between items-center mb-6 no-print">
        <button className="btn btn-outline flex items-center gap-2" onClick={() => navigate('/inventory')}>
          <ArrowLeft size={18} /> Back
        </button>
        <div className="flex gap-2">
          <button className="btn btn-outline text-primary border-primary p-2" onClick={handleShare}>
            <Share2 size={18} />
          </button>
          <button className="btn btn-primary flex items-center gap-2" onClick={handlePrint}>
            <Printer size={18} /> Print
          </button>
        </div>
      </div>

      <div 
        ref={receiptRef}
        className="receipt-box p-6 border rounded"
        style={{ borderColor: 'var(--border-color)', background: '#fff', color: '#000', fontFamily: 'monospace' }}
      >
        {/* Header */}
        <div className="text-center mb-6">
            {appSettings.logo && (
              <img 
                src={appSettings.logo} 
                alt="Logo" 
                className="receipt-logo"
                style={{ maxHeight: '40px', maxWidth: '40px', objectFit: 'contain', margin: '0 auto 10px auto', filter: 'grayscale(100%)' }}
              />
            )}
            <h1 className="text-xl font-bold uppercase">{appSettings.companyName || 'BREAD APP'}</h1>
            <p className="text-sm">SUPPLIER PAYMENT RECEIPT</p>
          </div>

          <div className="border-b border-dashed border-gray-400 pb-4 mb-4 text-sm">
            <div className="flex justify-between mb-1">
              <span>Receipt No:</span>
              <span className="font-bold">{payment.id.slice(-6).toUpperCase()}</span>
            </div>
            <div className="flex justify-between mb-1">
              <span>Date:</span>
              <span>{new Date(payment.date).toLocaleString()}</span>
            </div>
            <div className="flex justify-between mb-1">
              <span>Payment Method:</span>
              <span>{payment.method || 'Cash'}</span>
            </div>
            {payment.receiver && (
              <div className="flex justify-between">
                <span>Received By:</span>
                <span className="font-bold">{payment.receiver}</span>
              </div>
            )}
          </div>

          <div className="text-center mb-6">
            <div className="text-sm mb-1 uppercase tracking-wider">Amount Paid</div>
            <div className="text-3xl font-bold">₦{payment.amount.toLocaleString()}</div>
          </div>

          <div className="border-t border-dashed border-gray-400 pt-4 mb-6">
            <div className="flex justify-between text-sm">
              <span>Current Outstanding Balance:</span>
              <span className="font-bold">₦{currentBalance.toLocaleString()}</span>
            </div>
            <div className="flex justify-center mt-6" style={{ padding: '8px', background: '#fff', display: 'inline-block', border: '1px solid #eee', borderRadius: '4px' }}>
               <QRCode value={`bakery-receipt:${payment.id}`} size={64} level="L" />
            </div>
          </div>

          <div className="text-center text-xs text-gray-500 mt-8">
            <p>{appSettings.receiptFooter || 'Thank you for your business!'}</p>
            <p className="mt-1">Generated by BreadApp</p>
          </div>
        </div>
      
      <style>{`
        @media print {
          @page { margin: 0; size: 58mm auto; }
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            width: 58mm !important;
            background: #fff !important;
          }
          .no-print { display: none !important; }
          .container { 
            padding: 0 !important; 
            margin: 0 auto !important; 
            max-width: 58mm !important; 
            width: 58mm !important;
            box-shadow: none !important; 
            background: transparent !important;
          }
          
          .receipt-box {
            border: none !important; 
            padding: 4px !important; 
            margin: 0 auto !important;
            width: 58mm !important;
            max-width: 58mm !important;
            color: #000 !important;
            background: #fff !important;
            font-family: monospace !important;
            line-height: 1.2 !important;
            box-shadow: none !important;
          }
          .receipt-logo {
            max-width: 32px !important;
            max-height: 32px !important;
            margin: 0 auto 5px auto !important;
          }
          * {
            font-family: monospace !important;
            color: #000 !important;
          }
          h1 { font-size: 14px !important; margin-bottom: 2px !important; }
          .text-3xl { font-size: 14px !important; }
          .text-2xl { font-size: 14px !important; }
          .text-xl { font-size: 13px !important; }
          .text-lg { font-size: 12px !important; }
          .text-sm { font-size: 10px !important; }
          .text-xs { font-size: 9px !important; }
          .p-8 { padding: 4px !important; }
          .mb-6 { margin-bottom: 6px !important; }
          .mb-4 { margin-bottom: 4px !important; }
          .mt-8 { margin-top: 8px !important; }
        }
      `}</style>
    </div>
  );
};

export default BakeryReceipt;
