import React, { useEffect, useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppContext } from '../store/AppContext';
import type { DebtPayment, Customer } from '../store/types';
import { ArrowLeft, Printer, Share2 } from 'lucide-react';
import html2canvas from 'html2canvas';

import QRCodeImport from 'react-qr-code';
const QRCode = (QRCodeImport as any).default || QRCodeImport;

export const CustomerReceipt: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { debtPayments, customers, appSettings } = useAppContext();
  
  const [payment, setPayment] = useState<DebtPayment | null>(null);
  const [customer, setCustomer] = useState<Customer | null>(null);
  const receiptRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (id) {
      const foundPayment = debtPayments.find(p => p.id === id);
      if (foundPayment) {
        setPayment(foundPayment);
        const foundCustomer = customers.find(c => c.id === foundPayment.customerId);
        if (foundCustomer) {
          setCustomer(foundCustomer);
        }
      }
    }
  }, [id, debtPayments, customers]);

  if (!payment || !customer) {
    return (
      <div className="container p-6 text-center">
        <h2 className="text-xl font-bold mb-4">Receipt Not Found</h2>
        <button className="btn btn-primary" onClick={() => navigate('/customers')}>Back to Customers</button>
      </div>
    );
  }

  const handlePrint = async () => {
    try {
      // 1. Check if Web Bluetooth is supported in this browser
      if (!(navigator as any).bluetooth) {
        alert("This browser doesn't support direct Bluetooth printing. Falling back to standard print.");
        window.print();
        return;
      }

      // 2. Request a Bluetooth device (looking for common POS printer services or broadly accepting printers)
      const device = await (navigator as any).bluetooth.requestDevice({
        filters: [
          { services: ['000018f0-0000-1000-8000-00805f9b34fb'] }, // Common ESC/POS service UUID
          { namePrefix: 'MTP' },
          { namePrefix: 'PT' },
          { namePrefix: 'RP' },
          { namePrefix: 'Printer' }
        ],
        optionalServices: ['000018f0-0000-1000-8000-00805f9b34fb', '49535343-fe7d-4ae5-8fa9-9fafd205e455', 'e7810a71-73ae-499d-8c15-faa9aef0c3f2']
      });

      // 3. Connect to GATT Server
      if (!device.gatt) throw new Error("No GATT server found on the device.");
      const server = await device.gatt.connect();

      // 4. Get the primary Printing Service
      const services = await server.getPrimaryServices();
      if (services.length === 0) throw new Error("No services found on the printer.");
      const service = services[0]; // Usually the first one works for these mini printers

      // 5. Get the Characteristic (endpoint for writing data)
      const characteristics = await service.getCharacteristics();
      if (characteristics.length === 0) throw new Error("No characteristics found.");
      // Find a writable characteristic
      const characteristic = characteristics.find((c: any) => c.properties.write || c.properties.writeWithoutResponse);
      
      if (!characteristic) {
        throw new Error("No writable characteristic found on this printer.");
      }

      // --- ESC/POS COMMAND BUILDER ---
      // Basic ESC/POS generator
      const cmds = [
        "\\x1B" + "@", // Initialize printer
        "\\x1B" + "a" + "\\x01", // Center align
        "\\x1B" + "E" + "\\x01", // Bold On
        (appSettings.companyName || 'BREAD APP').toUpperCase() + "\n",
        "\\x1B" + "E" + "\\x00", // Bold Off
        "CUSTOMER PAYMENT RECEIPT\n",
        "--------------------------------\n", // 32 chars for 58mm
        "\\x1B" + "a" + "\\x00", // Left align
        `Receipt No: PAY-${payment.id.slice(-6).toUpperCase()}\n`,
        `Date: ${new Date(payment.date).toLocaleString()}\n`,
        `Customer: ${customer.name}\n`,
        customer.phone ? `Phone: ${customer.phone}\n` : "",
        `Method: ${payment.method || 'Cash'}\n`,
        "--------------------------------\n",
        "\\x1B" + "a" + "\\x01", // Center align
        "Amount Paid\n",
        "\\x1D" + "!" + "\\x11", // Double height & width
        `N ${payment.amount.toLocaleString()}\n`,
        "\\x1D" + "!" + "\\x00", // Normal text
        "\\x1B" + "a" + "\\x00", // Left align
        "--------------------------------\n",
        `New Balance: N ${customer.debtBalance.toLocaleString()}\n`,
        "\\x1B" + "a" + "\\x01", // Center align
        "\n",
        (appSettings.receiptFooter || 'Thank you for your business!') + "\n",
        "Generated by BreadApp\n",
        "\n\n\n" // Feed paper
      ].join("");

      // 6. Convert string to Uint8Array using TextEncoder.
      // Note: For real ESC/POS, handling special char bytes requires proper Uint8Array construction.
      // This is a simplified string-based approach that works for basic English text.
      // We manually parse the escaped hex codes back to bytes.
      
      const buffer = [];
      for (let i = 0; i < cmds.length; i++) {
        if (cmds[i] === '\\' && cmds[i+1] === 'x') {
           buffer.push(parseInt(cmds.substring(i+2, i+4), 16));
           i += 3;
        } else {
           buffer.push(cmds.charCodeAt(i));
        }
      }
      
      const payload = new Uint8Array(buffer);
      const chunkSize = 32; // Drop to 32 bytes for worst case BLE thermal printers
      for (let i = 0; i < payload.length; i += chunkSize) {
        const chunk = payload.slice(i, i + chunkSize);
        if (characteristic.properties.writeWithoutResponse) {
           await characteristic.writeValueWithoutResponse(chunk);
        } else {
           await characteristic.writeValue(chunk);
        }
        // Add a small delay to prevent buffer overflow on older printers
        await new Promise(resolve => setTimeout(resolve, 30)); // slightly larger delay
      }

      // Small delay before disconnect to ensure buffer flushes
      await new Promise(resolve => setTimeout(resolve, 500));

      // Disconnect cleanly
      device.gatt.disconnect();

    } catch (error) {
      console.warn('Bluetooth print failed or cancelled:', error);
      // Fallback
      window.print();
    }
  };

  const handleShare = async () => {
    if (!receiptRef.current) return;
    
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 2 });
      canvas.toBlob(async (blob) => {
        if (!blob) return;
        const file = new File([blob], `customer-receipt-${payment.id}.png`, { type: 'image/png' });
        
        if (navigator.share) {
          await navigator.share({
            title: 'Customer Payment Receipt',
            files: [file]
          });
        } else {
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `customer-receipt-${payment.id}.png`;
          a.click();
          URL.revokeObjectURL(url);
        }
      });
    } catch (err) {
      console.error('Error sharing receipt:', err);
      alert('Could not generate image for sharing.');
    }
  };

  return (
    <div className="container pb-20" style={{ maxWidth: '320px', margin: '0 auto', background: 'var(--surface-color)', minHeight: '100vh', paddingTop: '1rem' }}>
      {/* Hide controls when printing & optimize for 58mm POS */}
      <style>{`
        @media print {
          @page { margin: 0; size: 58mm auto; }
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            width: 58mm !important;
            background: #fff !important;
          }
          .no-print { display: none !important; }
          .container { 
            padding: 0 !important; 
            margin: 0 !important; 
            max-width: 58mm !important; 
            width: 58mm !important;
            box-shadow: none !important; 
            background: transparent !important;
          }
          .receipt-box { 
            border: none !important; 
            padding: 0 !important; 
            margin: 0 !important;
            width: 58mm !important;
            max-width: 58mm !important;
            color: #000 !important;
            background: #fff !important;
            font-family: monospace !important;
            line-height: 1.2 !important;
            box-shadow: none !important;
          }
          .receipt-logo {
            max-width: 28px !important;
            max-height: 28px !important;
            margin: 0 auto 4px auto !important;
          }
          * {
            font-family: monospace !important;
            color: #000 !important;
          }
          h1 { font-size: 14px !important; margin-bottom: 2px !important; }
          .text-3xl { font-size: 14px !important; }
          .text-xl { font-size: 13px !important; }
          .text-sm { font-size: 10px !important; }
          .text-xs { font-size: 9px !important; }
          .p-8 { padding: 5px !important; }
          .mb-6 { margin-bottom: 8px !important; }
          .mb-4 { margin-bottom: 5px !important; }
          .mt-8 { margin-top: 8px !important; }
          .pb-4 { padding-bottom: 4px !important; }
          .pt-4 { padding-top: 4px !important; }
        }
      `}</style>

      <div className="flex justify-between items-center mb-6 no-print">
        <button className="btn btn-outline btn-icon" onClick={() => navigate('/customers')}>
          <ArrowLeft size={18} />
        </button>
        <div className="flex gap-2">
          <button className="btn btn-outline text-primary border-primary flex items-center gap-2" onClick={handleShare} style={{ padding: '0.4rem 0.8rem' }}>
            <Share2 size={16} /> Share
          </button>
          <button className="btn btn-primary flex items-center gap-2" onClick={handlePrint} style={{ padding: '0.4rem 0.8rem' }}>
            <Printer size={16} /> Print
          </button>
        </div>
      </div>

      <div className="mx-auto" style={{ width: '100%' }}>
        <div 
          ref={receiptRef}
          className="receipt-box bg-white text-black p-6 rounded shadow-sm mx-auto"
          style={{ fontFamily: 'monospace', maxWidth: '100%' }}
        >
          {/* Header */}
          <div className="text-center mb-6">
            {appSettings.logo && (
              <img 
                src={appSettings.logo} 
                alt="Logo" 
                className="receipt-logo mx-auto mb-2 object-contain rounded-sm"
                style={{ filter: 'grayscale(100%)', width: '28px', height: '28px' }}
              />
            )}
            <h1 className="text-lg font-bold uppercase">{appSettings.companyName || 'BREAD APP'}</h1>
            <p className="text-xs">CUSTOMER PAYMENT RECEIPT</p>
          </div>

          <div className="border-b border-dashed border-gray-400 pb-4 mb-4 text-sm">
            <div className="flex justify-between mb-1">
              <span>Receipt No:</span>
              <span className="font-bold">PAY-{payment.id.slice(-6).toUpperCase()}</span>
            </div>
            <div className="flex justify-between mb-1">
              <span>Date:</span>
              <span>{new Date(payment.date).toLocaleString()}</span>
            </div>
            <div className="flex justify-between mb-1">
              <span>Customer:</span>
              <span className="font-bold">{customer.name}</span>
            </div>
            {customer.phone && (
              <div className="flex justify-between mb-1">
                <span>Phone:</span>
                <span>{customer.phone}</span>
              </div>
            )}
            <div className="flex justify-between">
              <span>Method:</span>
              <span>{payment.method || 'Cash'}</span>
            </div>
          </div>

          <div className="text-center mb-6">
            <div className="text-sm mb-1 uppercase tracking-wider">Amount Paid</div>
            <div className="text-3xl font-bold">₦{payment.amount.toLocaleString()}</div>
          </div>

          <div className="border-t border-dashed border-gray-400 pt-4 mb-6">
            <div className="flex justify-between text-sm">
              <span>New Outstanding Balance:</span>
              <span className="font-bold">₦{customer.debtBalance.toLocaleString()}</span>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', margin: '0 0 16px 0' }}>
            <div style={{ padding: '10px', background: '#fff', border: '2px solid #000', borderRadius: '6px', display: 'inline-block' }}>
              <QRCode value={`payment:${payment.id}`} size={100} level="M" />
            </div>
            <p style={{ fontSize: '9px', fontFamily: 'monospace', color: '#555', margin: 0 }}>Scan to view payment receipt</p>
          </div>

          <div className="text-center text-xs text-gray-500 mt-4">
            <p>{appSettings.receiptFooter || 'Thank you for your business!'}</p>
            <p className="mt-1">Generated by BreadApp</p>
          </div>
        </div>
      </div>
      
      <style>{`
        @media print {
          @page { margin: 0; size: 58mm auto; }
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            width: 58mm !important;
            background: #fff !important;
          }
          .no-print { display: none !important; }
          .container { 
            padding: 0 !important; 
            margin: 0 auto !important; 
            max-width: 58mm !important; 
            width: 58mm !important;
            box-shadow: none !important; 
            background: transparent !important;
          }
          .receipt-box { 
            border: none !important; 
            padding: 0 !important; 
            margin: 0 auto !important;
            width: 58mm !important;
            max-width: 58mm !important;
            color: #000 !important;
            background: #fff !important;
            font-family: monospace !important;
            line-height: 1.2 !important;
            position: absolute !important;
            left: 0 !important;
            top: 0 !important;
          }
          
          /* Show only the receipt content container and its children */
          .receipt-box, .receipt-box * {
            visibility: visible !important;
          }

          body * { visibility: hidden; }
        }
      `}</style>
    </div>
  );
};

export default CustomerReceipt;
