import React, { useRef, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppContext } from '../store/AppContext';
import { AnimatedPage } from '../components/AnimatedPage';
import { ArrowLeft, Printer, Share2, Download, FileText } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export const InventoryReceipt: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { inventoryLogs, products, appSettings } = useAppContext();
  const receiptRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);

  // Find all logs that belong to this batchId, or fallback to exact ID match for legacy single records
  const logs = inventoryLogs.filter(log => log.batchId === id || log.id === id);

  if (!logs || logs.length === 0) {
    return (
      <div className="container text-center mt-10">
        <h2>Receipt Not Found</h2>
        <button className="btn btn-primary mt-4" onClick={() => navigate('/inventory')}>Back to Inventory</button>
      </div>
    );
  }

  // Assuming all logs in a batch share the same date and type. We take the first one.
  const firstLog = logs[0];
  const type = firstLog.type || 'Receive';
  const totalValue = logs.reduce((sum, log) => sum + (log.quantityReceived * log.costPrice), 0);
  
  const handlePrint = async () => {
    try {
      if (!(navigator as any).bluetooth) {
        alert("This browser doesn't support direct Bluetooth printing. Falling back to standard print.");
        window.print();
        return;
      }

      const device = await (navigator as any).bluetooth.requestDevice({
        filters: [
          { services: ['000018f0-0000-1000-8000-00805f9b34fb'] },
          { namePrefix: 'MTP' },
          { namePrefix: 'PT' },
          { namePrefix: 'RP' },
          { namePrefix: 'Printer' }
        ],
        optionalServices: ['000018f0-0000-1000-8000-00805f9b34fb', '49535343-fe7d-4ae5-8fa9-9fafd205e455', 'e7810a71-73ae-499d-8c15-faa9aef0c3f2']
      });

      if (!device.gatt) throw new Error("No GATT server found.");
      const server = await device.gatt.connect();
      const services = await server.getPrimaryServices();
      if (services.length === 0) throw new Error("No services found.");
      const service = services[0];
      
      const characteristics = await service.getCharacteristics();
      const characteristic = characteristics.find((c: any) => c.properties.write || c.properties.writeWithoutResponse);
      if (!characteristic) throw new Error("No writable characteristic.");

      // Build ESC/POS payload
      const title = (appSettings.companyName || 'BREAD APP').toUpperCase();
      let cmds = [
        "\\x1B" + "@", // Init
        "\\x1B" + "a" + "\\x01", // Center
        "\\x1B" + "E" + "\\x01", // Bold
        title + "\n",
        "\\x1B" + "E" + "\\x00", // Normal
        `INVENTORY ${type.toUpperCase()} RECEIPT\n`,
        "--------------------------------\n", // 32 chars
        "\\x1B" + "a" + "\\x00", // Left
        `Ref: #${id?.substring(0, 8).toUpperCase() || 'N/A'}\n`,
        `Date: ${new Date(firstLog.date).toLocaleString()}\n`,
      ];
      
      if (firstLog.storeKeeper) cmds.push(`Keeper: ${firstLog.storeKeeper}\n`);
      cmds.push("--------------------------------\n");
      
      // Items
      logs.forEach(log => {
        const p = products.find(prod => prod.id === log.productId);
        const name = (p?.name || 'Item').substring(0, 16).padEnd(16, ' ');
        const qty = log.quantityReceived.toString().padStart(3, ' ');
        const price = (log.quantityReceived * log.costPrice).toLocaleString().padStart(9, ' ');
        cmds.push(`${name} x${qty} ${price}\n`);
      });
      
      cmds.push("--------------------------------\n");
      cmds.push("\\x1B" + "a" + "\\x02"); // Right align
      
      cmds.push("\\x1B" + "E" + "\\x01"); // Bold
      cmds.push("\\x1D" + "!" + "\\x11"); // Double height/width
      cmds.push(`TOTAL: NGN ${totalValue.toLocaleString()}\n`);
      cmds.push("\\x1D" + "!" + "\\x00"); // Normal
      cmds.push("\\x1B" + "E" + "\\x00"); // Unbold
      
      cmds.push("\\x1B" + "a" + "\\x01"); // Center
      cmds.push("\n");
      cmds.push((appSettings.receiptFooter || 'Thank you for your business!') + "\n");
      cmds.push("Generated by BreadApp\n");
      cmds.push("\n\n\n"); // Feed paper

      const cmdStr = cmds.join("");
      const buffer = [];
      for (let i = 0; i < cmdStr.length; i++) {
        if (cmdStr[i] === '\\' && cmdStr[i+1] === 'x') {
           buffer.push(parseInt(cmdStr.substring(i+2, i+4), 16));
           i += 3;
        } else {
           buffer.push(cmdStr.charCodeAt(i));
        }
      }
      
      const payload = new Uint8Array(buffer);
      const chunkSize = 32; // Drop to 32 bytes for worst case BLE thermal printers
      for (let i = 0; i < payload.length; i += chunkSize) {
        const chunk = payload.slice(i, i + chunkSize);
        if (characteristic.properties.writeWithoutResponse) {
           await characteristic.writeValueWithoutResponse(chunk);
        } else {
           await characteristic.writeValue(chunk);
        }
        await new Promise(r => setTimeout(r, 20)); // Strict slow down for printer BLE MTU
      }

      await new Promise(r => setTimeout(r, 500));
      device.gatt.disconnect();

    } catch (error) {
      console.warn("Bluetooth print failed: ", error);
      window.print();
    }
  };
  
  const handleShareText = () => {
    let text = `*${appSettings.companyName} - Inventory ${type}*\n`;
    text += `Date: ${new Date(firstLog.date).toLocaleString()}\n`;
    text += `Ref: ${id?.substring(0, 8) || 'N/A'}\n\n`;
    text += `*Items:*\n`;
    
    logs.forEach(log => {
      const p = products.find(prod => prod.id === log.productId);
      text += `- ${p?.name || 'Unknown Item'} x${log.quantityReceived} @ ₦${log.costPrice.toLocaleString()} = ₦${(log.quantityReceived * log.costPrice).toLocaleString()}\n`;
    });
    
    text += `\n*Total Value: ₦${totalValue.toLocaleString()}*\n`;
    
    const url = `whatsapp://send?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const exportAsImage = async () => {
    if (!receiptRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 2, useCORS: true, logging: false });
      const image = canvas.toDataURL("image/png", 1.0);
      
      // Try native share first for mobile
      if (navigator.share) {
        try {
          const blob = await (await fetch(image)).blob();
          const file = new File([blob], `inventory_${type}_${id?.substring(0,8)}.png`, { type: 'image/png' });
          await navigator.share({
            title: `Inventory ${type} Receipt`,
            files: [file]
          });
          setIsExporting(false);
          return;
        } catch (err) {
          console.log("Native share failed or unsupported, falling back to download", err);
        }
      }

      // Fallback: Download the file manually
      const link = document.createElement('a');
      link.download = `inventory_${type}_${id?.substring(0,8)}.png`;
      link.href = image;
      link.click();
      alert("Image downloaded! You can now attach it in WhatsApp.");
    } catch (error) {
      console.error("Failed to export image", error);
      alert("Failed to export image.");
    }
    setIsExporting(false);
  };

  const exportAsPDF = async () => {
    if (!receiptRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 2, useCORS: true, logging: false });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width / 2, canvas.height / 2] // Attempt to map pixel dimensions nicely
      });
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
      
      // Try native share first
      if (navigator.share) {
        try {
          const blob = pdf.output('blob');
          const file = new File([blob], `inventory_${type}_${id?.substring(0,8)}.pdf`, { type: 'application/pdf' });
          await navigator.share({
            title: `Inventory ${type} Receipt`,
            files: [file]
          });
          setIsExporting(false);
          return;
        } catch (err) {
          console.log("Native PDF share failed, falling back to download");
        }
      }

      pdf.save(`inventory_${type}_${id?.substring(0,8)}.pdf`);
      alert("PDF downloaded! You can now attach it in WhatsApp.");
    } catch (error) {
      console.error("Failed to export PDF", error);
      alert("Failed to create PDF.");
    }
    setIsExporting(false);
  };

  return (
    <AnimatedPage>
      {/* 58mm POS Optimization */}
      <style>{`
        @media print {
          @page { margin: 0; size: 58mm auto; }
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            width: 58mm !important;
            background: #fff !important;
          }
          .no-print { display: none !important; }
          .container { 
            padding: 0 !important; 
            margin: 0 auto !important; 
            max-width: 58mm !important; 
            width: 58mm !important;
            box-shadow: none !important; 
            background: transparent !important;
          }
          .receipt-box { 
            border: none !important; 
            padding: 0 !important; 
            margin: 0 auto !important;
            width: 58mm !important;
            max-width: 58mm !important;
            color: #000 !important;
            background: #fff !important;
            font-family: monospace !important;
            line-height: 1.2 !important;
          }
          * {
            font-family: monospace !important;
            color: #000 !important;
          }
          h1 { font-size: 14px !important; margin-bottom: 2px !important; }
          .text-2xl { font-size: 14px !important; }
          .text-xl { font-size: 13px !important; }
          .text-lg { font-size: 12px !important; }
          .text-sm { font-size: 10px !important; }
          .text-xs { font-size: 9px !important; }
          .p-6 { padding: 5px !important; }
          .mb-6 { margin-bottom: 8px !important; }
          .mb-4 { margin-bottom: 5px !important; }
          .py-3 { padding-top: 3px !important; padding-bottom: 3px !important; }
          .p-3 { padding: 3px !important; }
          .border-dashed { border-style: dashed !important; border-width: 1px !important; border-color: #000 !important; }
        }
      `}</style>
      <div className="container" style={{ maxWidth: '320px', margin: '0 auto', background: 'var(--surface-color)', minHeight: '100vh', paddingTop: '1rem' }}>

        <div className="flex justify-between items-center mb-6 no-print">
          <button onClick={() => navigate(-1)} className="btn btn-outline btn-icon">
             <ArrowLeft size={20} />
          </button>
          <button onClick={handlePrint} className="btn btn-primary" style={{ width: 'auto', minHeight: '2.5rem', padding: '0.5rem 1rem' }}>
            <Printer size={18} className="mr-2" style={{marginRight: '0.5rem'}} /> Print
          </button>
        </div>

        <div ref={receiptRef} className="receipt-box p-6 border rounded" style={{ borderColor: 'var(--border-color)', background: '#fff', color: '#000' }}>
          <div className="text-center mb-6 border-b pb-4 border-dashed" style={{ borderColor: '#ddd' }}>
            {appSettings.logo && (
              <img 
                src={appSettings.logo} 
                alt="Logo" 
                className="receipt-logo"
                style={{ maxHeight: '60px', maxWidth: '80%', objectFit: 'contain', margin: '0 auto 10px auto' }} 
              />
            )}
            <h1 className="text-2xl font-bold mb-1 font-mono uppercase text-black">{appSettings.companyName}</h1>
            <p className="text-sm font-mono mt-1 text-gray-600 border border-gray-300 border-dashed inline-block p-1 uppercase">
              INVENTORY {type} RECEIPT
            </p>
          </div>
          
          <div className="text-sm space-y-1 mb-6 font-mono text-gray-700">
            <div className="flex justify-between">
              <span>Date:</span>
              <span>{new Date(firstLog.date).toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span>Ref ID:</span>
              <span>{id?.substring(0, 8)}</span>
            </div>
          </div>
          
          <div className="border-t border-b py-3 mb-4 border-dashed" style={{ borderColor: '#ddd' }}>
            <table className="w-full text-sm font-mono text-gray-800">
              <thead>
                <tr className="border-b border-gray-300 border-dashed">
                  <th className="text-left pb-2">Item</th>
                  <th className="text-center pb-2">Qty</th>
                  <th className="text-right pb-2">Cost</th>
                  <th className="text-right pb-2">Total</th>
                </tr>
              </thead>
              <tbody>
                {logs.map((log) => {
                  const product = products.find(p => p.id === log.productId);
                  return (
                    <tr key={log.id} className="border-b border-gray-100 border-dashed">
                      <td className="py-2 text-left">{product?.name || 'Unknown'}</td>
                      <td className="py-2 text-center">{log.quantityReceived}</td>
                      <td className="py-2 text-right">{log.costPrice}</td>
                      <td className="py-2 text-right">{(log.quantityReceived * log.costPrice).toLocaleString()}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          
          <div className="flex justify-between text-xl font-bold mb-6 font-mono text-black">
            <span>TOTAL VALUE</span>
            <span>₦{totalValue.toLocaleString()}</span>
          </div>
          
          <div className="text-center text-sm border-t border-dashed pt-4 font-mono" style={{ borderColor: '#aaa' }}>
            {appSettings.receiptFooter ? (
              <p style={{ whiteSpace: 'pre-line' }}>{appSettings.receiptFooter}</p>
            ) : (
              <p>For Internal Store Use</p>
            )}
            <p className="text-xs opacity-60 mt-2">System Generated Receipt</p>
          </div>
        </div>

        <div className="flex flex-col gap-2 mt-4 mb-10 no-print">
          <button className="btn btn-outline w-full py-3 justify-center text-success border-success" onClick={handleShareText}>
            <Share2 size={18} className="mr-2" /> Share as Text (WhatsApp)
          </button>
          <div className="flex gap-2">
            <button className="btn btn-primary flex-1 py-3 justify-center text-sm" onClick={exportAsImage} disabled={isExporting}>
              <Download size={16} className="mr-2" /> {isExporting ? '...' : 'Save Image'}
            </button>
            <button className="btn btn-primary flex-1 py-3 justify-center text-sm" onClick={exportAsPDF} disabled={isExporting}>
              <FileText size={16} className="mr-2" /> {isExporting ? '...' : 'Save PDF'}
            </button>
          </div>
        </div>

      </div>
    </AnimatedPage>
  );
};

export default InventoryReceipt;
