import React, { useEffect, useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppContext } from '../store/AppContext';
import { supabase } from '../lib/supabase';
import { getTransactionItems } from '../store/types';
import { Printer, ArrowLeft, Share2, Download, FileText } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import QRCodeImport from 'react-qr-code';
const QRCode = (QRCodeImport as any).default || QRCodeImport;

export const Receipt: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { transactions, products, customers, appSettings } = useAppContext();
  
  const receiptRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  
  const [tx, setTx] = useState(transactions.find(t => t.id === id));
  const [keeperName, setKeeperName] = useState<string | null>(null);
 
  useEffect(() => {
    const transaction = transactions.find(t => t.id === id);
    setTx(transaction);
    
    if (transaction?.storeKeeperId) {
       supabase.from('profiles').select('full_name').eq('id', transaction.storeKeeperId).single().then(({ data }) => {
          if (data) setKeeperName(data.full_name);
       });
    }
  }, [id, transactions]);

  if (!tx) {
    return <div className="container mt-8 text-center">Receipt not found.</div>;
  }

  const customer = customers.find(c => c.id === tx.customerId);

  const handlePrint = async () => {
    try {
      if (!(navigator as any).bluetooth) {
        alert("This browser doesn't support direct Bluetooth printing. Falling back to standard print.");
        window.print();
        return;
      }

      const device = await (navigator as any).bluetooth.requestDevice({
        filters: [
          { services: ['000018f0-0000-1000-8000-00805f9b34fb'] },
          { namePrefix: 'MTP' },
          { namePrefix: 'PT' },
          { namePrefix: 'RP' },
          { namePrefix: 'Printer' }
        ],
        optionalServices: ['000018f0-0000-1000-8000-00805f9b34fb', '49535343-fe7d-4ae5-8fa9-9fafd205e455', 'e7810a71-73ae-499d-8c15-faa9aef0c3f2']
      });

      if (!device.gatt) throw new Error("No GATT server found.");
      const server = await device.gatt.connect();
      const services = await server.getPrimaryServices();
      if (services.length === 0) throw new Error("No services found.");
      const service = services[0];
      
      const characteristics = await service.getCharacteristics();
      const characteristic = characteristics.find((c: any) => c.properties.write || c.properties.writeWithoutResponse);
      if (!characteristic) throw new Error("No writable characteristic.");

      // Build ESC/POS payload
      const title = (appSettings.companyName || 'BREAD APP').toUpperCase();
      let cmds = [
        "\\x1B" + "@", // Init
        "\\x1B" + "a" + "\\x01", // Center
        "\\x1B" + "E" + "\\x01", // Bold
        title + "\n",
        "\\x1B" + "E" + "\\x00", // Normal
        "SALES RECEIPT\n",
        "--------------------------------\n", // 32 chars
        "\\x1B" + "a" + "\\x00", // Left
        `Ref: #${tx.id.slice(-6).toUpperCase()}\n`,
        `Date: ${new Date(tx.date).toLocaleString()}\n`,
      ];
      
      if (customer) cmds.push(`Customer: ${customer.name}\n`);
      cmds.push("--------------------------------\n");
      
      // Items
      getTransactionItems(tx).forEach(item => {
        const p = products.find(prod => prod.id === item.productId);
        const name = (p?.name || 'Item').substring(0, 13).padEnd(13, ' ');
        const qty = item.quantity.toString().padStart(3, ' ');
        const price = (item.quantity * item.unitPrice).toLocaleString().padStart(8, ' ');
        cmds.push(`${name} x${qty} ${price}\n`);
      });
      
      cmds.push("--------------------------------\n");
      cmds.push("\\x1B" + "a" + "\\x02"); // Right align
      
      if (tx.discount && tx.discount > 0) {
        cmds.push(`Discount: -N ${tx.discount.toLocaleString()}\n`);
      }
      
      cmds.push("\\x1B" + "E" + "\\x01"); // Bold
      cmds.push("\\x1D" + "!" + "\\x11"); // Double height/width
      cmds.push(`TOTAL: N ${tx.totalPrice.toLocaleString()}\n`);
      cmds.push("\\x1D" + "!" + "\\x00"); // Normal
      cmds.push("\\x1B" + "E" + "\\x00"); // Unbold
      
      cmds.push("\\x1B" + "a" + "\\x00"); // Left align
      cmds.push(`Payment: ${tx.type}\n`);
      
      cmds.push("\\x1B" + "a" + "\\x01"); // Center
      cmds.push("\n");
      cmds.push((appSettings.receiptFooter || 'Thank you for your business!') + "\n");
      cmds.push("Generated by BreadApp\n");
      cmds.push("\n\n\n"); // Feed paper

      const cmdStr = cmds.join("");
      const buffer = [];
      for (let i = 0; i < cmdStr.length; i++) {
        if (cmdStr[i] === '\\' && cmdStr[i+1] === 'x') {
           buffer.push(parseInt(cmdStr.substring(i+2, i+4), 16));
           i += 3;
        } else {
           buffer.push(cmdStr.charCodeAt(i));
        }
      }
      
      const payload = new Uint8Array(buffer);
      const chunkSize = 32; // Hyper-conservative for worst-case BLE thermal printers
      for (let i = 0; i < payload.length; i += chunkSize) {
        const chunk = payload.slice(i, i + chunkSize);
        if (characteristic.properties.writeWithoutResponse) {
           await characteristic.writeValueWithoutResponse(chunk);
        } else {
           await characteristic.writeValue(chunk);
        }
        await new Promise(r => setTimeout(r, 20)); // Strict slow down for printer BLE MTU
      }

      await new Promise(r => setTimeout(r, 500));
      device.gatt.disconnect();

    } catch (error) {
      console.warn("Bluetooth print failed: ", error);
      window.print();
    }
  };

  const handleShareText = () => {
    let text = `*${appSettings.companyName} - Sales Receipt*\n`;
    text += `Date: ${dateStr} ${timeStr}\n`;
    text += `Ref: #${tx.id.slice(-6)}\n`;
    if (customer?.name) text += `Customer: ${customer.name}\n`;
    text += `\n*Items:*\n`;
    
    getTransactionItems(tx).forEach(item => {
      const p = products.find(prod => prod.id === item.productId);
      text += `- ${p?.name || 'Item'} x${item.quantity} @ ₦${item.unitPrice.toLocaleString()} = ₦${(item.quantity * item.unitPrice).toLocaleString()}\n`;
    });
    
    if (tx.discount && tx.discount > 0) {
      text += `\nDiscount: -₦${tx.discount.toLocaleString()}`;
    }
    
    text += `\n*Total: ₦${tx.totalPrice.toLocaleString()}*\n`;
    text += `Payment: ${tx.type}\n`;
    
    const url = `whatsapp://send?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const exportAsImage = async () => {
    if (!receiptRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 2, useCORS: true, logging: false });
      const image = canvas.toDataURL("image/png", 1.0);
      
      if (navigator.share) {
        try {
          const blob = await (await fetch(image)).blob();
          const file = new File([blob], `sales_${id?.substring(0,8)}.png`, { type: 'image/png' });
          await navigator.share({ title: `Sales Receipt`, files: [file] });
          setIsExporting(false);
          return;
        } catch (err) { console.log(err); }
      }

      const link = document.createElement('a');
      link.download = `sales_${id?.substring(0,8)}.png`;
      link.href = image;
      link.click();
    } catch (error) {
      alert("Failed to export image.");
    }
    setIsExporting(false);
  };

  const exportAsPDF = async () => {
    if (!receiptRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(receiptRef.current, { scale: 2, useCORS: true, logging: false });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width / 2, canvas.height / 2]
      });
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
      
      if (navigator.share) {
        try {
          const blob = pdf.output('blob');
          const file = new File([blob], `sales_${id?.substring(0,8)}.pdf`, { type: 'application/pdf' });
          await navigator.share({ title: `Sales Receipt`, files: [file] });
          setIsExporting(false);
          return;
        } catch (err) { console.log(err); }
      }

      pdf.save(`sales_${id?.substring(0,8)}.pdf`);
    } catch (error) {
      alert("Failed to create PDF.");
    }
    setIsExporting(false);
  };

  const d = new Date(tx.date);
  const dateStr = d.toLocaleDateString();
  const timeStr = d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  return (
    <div className="container" style={{ maxWidth: '320px', margin: '0 auto', background: 'var(--surface-color)', minHeight: '100vh', paddingTop: '1rem' }}>
      
      {/* 58mm POS Optimization */}
      <style>{`
        @media print {
          @page { margin: 0; size: 58mm auto; }
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            width: 58mm !important;
            background: #fff !important;
          }
          .no-print { display: none !important; }
          .container { 
            padding: 0 !important; 
            margin: 0 auto !important; 
            max-width: 58mm !important; 
            width: 58mm !important;
            box-shadow: none !important; 
            background: transparent !important;
          }
          .receipt-box { 
            border: none !important; 
            padding: 0 !important; 
            margin: 0 auto !important;
            width: 58mm !important;
            max-width: 58mm !important;
            color: #000 !important;
            background: #fff !important;
            font-family: monospace !important;
            line-height: 1.2 !important;
          }
          .receipt-logo {
            max-width: 32px !important;
            max-height: 32px !important;
            margin: 0 auto 5px auto !important;
          }
          * {
            font-family: monospace !important;
            color: #000 !important;
          }
          h1 { font-size: 14px !important; margin-bottom: 2px !important; }
          .text-2xl { font-size: 14px !important; }
          .text-xl { font-size: 13px !important; }
          .text-lg { font-size: 12px !important; }
          .text-sm { font-size: 10px !important; }
          .text-xs { font-size: 9px !important; }
          .p-6 { padding: 4px !important; }
          .mb-6 { margin-bottom: 6px !important; }
          .mb-4 { margin-bottom: 4px !important; }
          .py-3 { padding-top: 3px !important; padding-bottom: 3px !important; }
          .p-3 { padding: 3px !important; }

          /* CRITICAL: Force QR Code SVG to print correctly */
          svg { display: block !important; print-color-adjust: exact !important; -webkit-print-color-adjust: exact !important; }
          svg rect, svg path { fill: #000 !important; }
          svg > rect:first-child { fill: #fff !important; }
          svg * { color: inherit !important; }
        }
      `}</style>
      
      <div className="flex justify-between items-center mb-6 no-print">
        <button onClick={() => navigate(-1)} className="btn btn-outline btn-icon">
           <ArrowLeft size={20} />
        </button>
        <button onClick={handlePrint} className="btn btn-primary" style={{ width: 'auto', minHeight: '2.5rem', padding: '0.5rem 1rem' }}>
          <Printer size={18} className="mr-2" style={{marginRight: '0.5rem'}} /> Print
        </button>
      </div>

      {/* Printable Receipt Area */}
      <div ref={receiptRef} className="receipt-box p-6 border rounded" style={{ borderColor: 'var(--border-color)', background: '#fff', color: '#000' }}>
        <div className="text-center mb-6 border-b pb-4 border-dashed" style={{ borderColor: '#ddd' }}>
          {appSettings.logo && (
            <img 
              src={appSettings.logo} 
              alt="Logo" 
              className="receipt-logo"
              style={{ maxHeight: '60px', maxWidth: '80%', objectFit: 'contain', margin: '0 auto 10px auto' }} 
            />
          )}
          <h1 className="text-2xl font-bold mb-1 font-mono uppercase text-black">{appSettings.companyName}</h1>
          <p className="text-sm font-mono mt-1 text-gray-600 border border-gray-300 border-dashed inline-block p-1 uppercase">SALES RECEIPT</p>
        </div>

        <div className="flex justify-between text-sm mb-4">
          <div>
            <div><strong>Date:</strong> {dateStr}</div>
            <div><strong>Time:</strong> {timeStr}</div>
          </div>
          <div className="text-right">
            <div><strong>Txn ID:</strong> #{tx.id.slice(-6)}</div>
          </div>
        </div>

        <div className="mb-6 p-3" style={{ background: '#f5f5f5', borderRadius: '4px' }}>
          <div className="text-sm font-bold mb-1">Customer:</div>
          <div className="text-lg">{customer?.name || 'Unknown'}</div>
          {customer?.phone && <div className="text-sm">{customer.phone}</div>}
          {keeperName && (
             <div className="text-xs mt-2 border-t pt-1" style={{ borderColor: '#e5e7eb' }}>
                <strong>Staff:</strong> {keeperName}
             </div>
          )}
        </div>

        <div className="text-sm opacity-80 mb-4">{new Date(tx.date).toLocaleString()}</div>
        
        <div className="border-t border-b py-3 mb-4" style={{ borderColor: 'var(--border-color)' }}>
          {getTransactionItems(tx).map((item, idx) => {
            const product = products.find(p => p.id === item.productId);
            return (
              <div key={idx} className="mb-2">
                <div className="flex justify-between font-bold">
                  <span>{product?.name || 'Item'}</span>
                  <span>₦{(item.quantity * item.unitPrice).toLocaleString()}</span>
                </div>
                <div className="text-sm opacity-80">
                  Qty: {item.quantity} @ ₦{item.unitPrice}
                </div>
              </div>
            );
          })}
          
          {tx.discount && tx.discount > 0 && (
            <div className="flex justify-between text-sm text-danger font-bold mt-2 pt-2 border-t" style={{ borderColor: 'var(--border-color)' }}>
              <span>Discount</span>
              <span>- ₦{tx.discount.toLocaleString()}</span>
            </div>
          )}
        </div>
        
        <div className="flex justify-between text-xl font-bold mb-6">
          <span>TOTAL</span>
          <span>₦{tx.totalPrice.toLocaleString()}</span>
        </div>

        <div className="text-center mb-6">
          <div className="text-sm mb-1">Payment Method</div>
          <div className="font-bold text-lg uppercase mb-4" style={{ color: tx.type === 'Cash' ? '#16a34a' : '#000' }}>
            {tx.type}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px' }}>
            <div style={{ padding: '10px', background: '#fff', border: '2px solid #000', borderRadius: '6px', display: 'inline-block' }}>
               <QRCode value={`receipt:${tx.id}`} size={100} level="M" />
            </div>
            <p style={{ fontSize: '9px', fontFamily: 'monospace', color: '#555', margin: 0 }}>Scan to view receipt</p>
          </div>
        </div>

        <div className="text-center text-sm border-t border-dashed pt-4" style={{ borderColor: '#aaa' }}>
          {appSettings.receiptFooter ? (
            <p style={{ whiteSpace: 'pre-line' }}>{appSettings.receiptFooter}</p>
          ) : (
            <p>Thank you for your business!</p>
          )}
          <p className="text-xs opacity-60 mt-2">System Generated Receipt</p>
        </div>
      </div>

      <div className="flex flex-col gap-2 mt-4 mb-10 no-print">
        <button className="btn btn-outline w-full py-3 justify-center text-success border-success" onClick={handleShareText}>
          <Share2 size={18} className="mr-2" /> Share as Text (WhatsApp)
        </button>
        <div className="flex gap-2">
          <button className="btn btn-primary flex-1 py-3 justify-center text-sm" onClick={exportAsImage} disabled={isExporting}>
            <Download size={16} className="mr-2" /> {isExporting ? '...' : 'Save Image'}
          </button>
          <button className="btn btn-primary flex-1 py-3 justify-center text-sm" onClick={exportAsPDF} disabled={isExporting}>
            <FileText size={16} className="mr-2" /> {isExporting ? '...' : 'Save PDF'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default Receipt;
